
name: Weather Data Workflow

on:
  schedule:
    - cron: '0 8 * * *' # Runs daily at 8 AM UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  fetch-weather:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      
      - name: Run weather.sh script
        run: |
          chmod +x weather.sh  # Make it executable
          ./weather.sh         # Run the script

      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add weather_data.txt
          git commit -m "Automated weather data update" || echo "No changes to commit"
          git push
          